---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - flux.gh-release-operator.com
  resources:
  - helmdeploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flux.gh-release-operator.com
  resources:
  - helmdeploys/finalizers
  verbs:
  - update
- apiGroups:
  - flux.gh-release-operator.com
  resources:
  - helmdeploys/status
  verbs:
  - get
  - patch
  - update
